# 商用程式設計：第四章　Python串列物件
### Chap 4(109/03/31)
* List：串列 [ ]
* Tuple：固定串列 ( ) 簡稱:元組
* Dict：有鍵值(Key)的串列 { }

In [1]:
#Dictionary(Dict) 字典：帶有鍵值（Key）的串列（list）
Ianguages = {'name':'python', 'version':'3.7'} #索引值（鍵值）可以自訂
print(Ianguages['name'])
print(Ianguages['version'])
a = {0:'python', 1:'Java', 2:'SQL'}
for i in range(0,3):
    print(a[i])
print(Ianguages)
print(Ianguages.keys())
print(Ianguages.values())
print(Ianguages.items())
print('name' in Ianguages)

python
3.7
python
Java
SQL
{'name': 'python', 'version': '3.7'}
dict_keys(['name', 'version'])
dict_values(['python', '3.7'])
dict_items([('name', 'python'), ('version', '3.7')])
True


In [2]:
a = {'name':'python', 'version':'3.7'}
print(a)
b = a.copy()
print(b)
b.clear()
print(b)
print(a['name'])
print(a.get('name'))
a.update({'name':'Java'})
print(a)

{'name': 'python', 'version': '3.7'}
{'name': 'python', 'version': '3.7'}
{}
python
python
{'name': 'Java', 'version': '3.7'}


# 商用程式設計：第五章　Numpy套件
## Numpy套件的ndarray型態，提供element-wise的操作
### Chap 5(109/03/31)

In [9]:
a = [1,2,3,4,5]
print(a * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [10]:

import numpy as np
b = np.array([1,2,3,4,5])
print(b * 3)

[ 3  6  9 12 15]


In [13]:
print(type(b))
print(b.ndim) #ndarray的維度
print(b.shape) #ndarray的範圍
print(b.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [30]:
print(np.zeros(6)) #產生6個元素均為0的一維array
print("----------------------------")
print(np.zeros((3, 6))) #產生18個元素均為0的二維array
print("----------------------------")
print(np.zeros((2, 3, 6))) #產生36個元素均為0的三維array
print("----------------------------")
print(np.zeros((2, 2, 3, 6))) #產生72個元素均為0的四維array

[0. 0. 0. 0. 0. 0.]
----------------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
----------------------------
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
----------------------------
[[[[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]]


In [31]:
a = np.zeros(16)
print(a)
print(a.shape)
b = a.reshape((4, 4)) #改變資料的維度維4*4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


In [32]:
my_array = np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5]) #[0,1,2,3,4]位置的值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [39]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b = np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c = np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
